### ISSUE TITLE
Ecco il file che rende confrontabili le elezioni 2013 con quelle del 2018

### ISSUE THREAD

**Issue by sapomnia** [ondata/elezionipolitiche2013#3]
L'ho fatto per la Camera e per solo alcune delle liste che si presentarono cinque anni fa (Pd, M5S, Sel, Pdl, FdI, Lega, Casapound). Ho creato un file per riconciliare i comuni soppressi o che si sono fusi, sommando poi i voti ottenuti da ciascuna lista in questi comuni. Ho aggiunto il totale dei voti validi e ho ricalcolato le percentuali.
[Risultati camera 2013 confrontabili.xlsx](https://github.com/ondata/elezionipolitiche2013/files/1777886/Risultati.camera.2013.confrontabili.xlsx)

**Comment by aborruso** [comment]
Ottimo. Ho aggiunto tutto nel repo e creato nel README sezione [Elaborazioni](https://github.com/ondata/elezionipolitiche2013#elaborazioni)
